### Get all categories
GET http://localhost:8080/api/categories
X-API-Key: SECRET
Accept: application/json

### Create new categories
POST http://localhost:8080/api/categories
X-API-Key: SECRET
Accept: application/json
Content-Type: application/json

{
  "name": "Chair"
}

### Get category by Id
GET http://localhost:8080/api/categories/1
X-API-Key: SECRET
Accept: application/json

### Update category by Id
PUT http://localhost:8080/api/categories/2
X-API-Key: SECRET
Accept: application/json
Content-Type: application/json

{
  "name": "Fashion"
}

### Delete category by Id
DELETE http://localhost:8080/api/categories/1
X-API-Key: SECRET
Accept: application/json